language: go
go:
  - 1.3
notifications:
  email:
    recipients:
      - stevenmajack@gmail.com
    on_failure: change
    on_success: never
sudo: false
install:
  - "go get github.com/mitchellh/gox"
  - "gox -build-toolchain"
script:
  - "gox"
